src/Entity/Citation.php
<?php

/**
 * Nom du fichier : Citation.php
 * Description : Ce fichier contient la classe Citation qui représente une entité citation.
 */

namespace App\Entity;

use App\Entity\Trait\DateModifTrait;
use App\Repository\CitationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * Class Citation
 * Cette classe représente une citation.
 */
#[ORM\Entity(repositoryClass: CitationRepository::class)]
#[ORM\Table(name: 'citations')]
class Citation
{
    use DateModifTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(["getCitation", "getAuteur"])]
    private ?int $id = null;

    #[ORM\Column(length: 511)]
    #[Groups(["getCitation", "getAuteur"])]
    private ?string $citation = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Groups(["getCitation", "getAuteur"])]
    private ?string $explication = null;

    #[ORM\ManyToOne(inversedBy: 'citations')]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    #[Groups(["getCitation"])]
    private ?Auteur $auteur_id = null;

    public function __construct()
    {
        $this->date_modif = new \DateTime();
    }

    /**
     * Obtient l'identifiant de la citation.
     *
     * @return int|null L'identifiant de la citation
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Obtient la citation.
     *
     * @return string|null La citation
     */
    public function getCitation(): ?string
    {
        return html_entity_decode($this->citation);
    }

    /**
     * Définit la citation.
     *
     * @param string $citation La citation
     * @return static L'instance de la citation
     */
    public function setCitation(string $citation): static
    {
        $this->citation = $citation;

        return $this;
    }

    /**
     * Obtient l'explication de la citation.
     *
     * @return string|null L'explication de la citation
     */
    public function getExplication(): ?string
    {
        return html_entity_decode($this->explication);
    }

    /**
     * Définit l'explication de la citation.
     *
     * @param string|null $explication L'explication de la citation
     * @return static L'instance de la citation
     */
    public function setExplication(?string $explication): static
    {
        $this->explication = $explication;

        return $this;
    }

    /**
     * Obtient l'auteur de la citation.
     *
     * @return Auteur|null L'auteur de la citation
     */
    public function getAuteurId(): ?Auteur
    {
        return $this->auteur_id;
    }

    /**
     * Définit l'auteur de la citation.
     *
     * @param Auteur|null $auteur_id L'auteur de la citation
     * @return static L'instance de la citation
     */
    public function setAuteurId(?Auteur $auteur_id): static
    {
        $this->auteur_id = $auteur_id;

        return $this;
    }
}

src/Controller/CitationsController.php
<?php

/**
 * Nom du fichier : CitationsController.php
 * Description : Ce fichier contient la classe CitationsController qui gère les fonctionnalités des citations.
 */

namespace App\Controller;

use App\Entity\Citation;
use App\Form\CitationFormType;
use App\Repository\AuteurRepository;
use App\Repository\CitationRepository;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Contrôleur CitationsController
 * Gère les fonctionnalités CRUD liées aux citations.
 */
class CitationsController extends AbstractController
{
    private $citationRepository;
    private $citations;
    private $auteurRepository;

    /**
     * Initialisation de la classe avec injection des dépendances
     * 
     * @param CitationRepository $citationRepository Le repository des citations.
     * @param AuteurRepository $auteurRepository Le repository des auteurs.
     */
    public function __construct(CitationRepository $citationRepository, AuteurRepository $auteurRepository)
    {
        $this->auteurRepository = $auteurRepository;
        $this->citationRepository = $citationRepository;

        // Récupération des citations classées par auteur
        $this->citations = $citationRepository->createQueryBuilder('c')
            ->leftJoin('c.auteur_id', 'a')
            ->orderBy('a.auteur', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Affiche la liste des citations regroupées par auteur
     * 
     * @return Response Vue Twig affichant la liste des citations classées par auteur.
     */
    #[Route('/citations', name: 'app_citations')]
    public function index(): Response
    {
        return $this->render('citations/index.html.twig', [
            'controller_name' => 'CitationsController',
            'auteurs' => $this->auteurRepository->findBy([], ['auteur' => 'asc']),
            'citations' => $this->citations
        ]);
    }

    /**
     * Affiche les détails d'une citation sélectionnée par son ID
     * 
     * @param int $id ID de la citation.
     * @return Réponse Vue Twig affichant les détails de la citation.
     */
    #[Route('/citation/details/{id}', name: 'app_citations_detail')]
    public function detail(int $id): Response
    {
        // Retour sur la page d'index avec un message d'erreur en cas de citation introuvable
        if (!$this->citationRepository->find($id)) {
            $this->addFlash('danger', 'Action impossible : Référence inexistante.');
            return $this->redirectToRoute('app_citations');
        }
        // Appel de la vue détaillée
        return $this->render('citations/detail.html.twig', [
            'controller_name' => 'CitationsController',
            'citation' => $this->citationRepository->find($id)
        ]);
    }

    /**
     * Modifie une citation existante sélectionnée par son ID.
     * 
     * @param int $id L'ID de la citation.
     * @param Request $request Modifications à apporter à la citation, transmises via POST.
     * @return Reponse Vue Twig affichant un formulaire de modification ou un message.
     */
    #[Route('/citation/modifier/{id}', name: 'app_citations_modifier')]
    public function modification(int $id, Request $request): Response
    {
        // Récupération de la citation
        $citation = $this->citationRepository->find($id);

        // Récupération de la liste des auteurs
        $auteurs = $this->auteurRepository->findBy([], ['auteur' => 'ASC']);

        // Retour sur la page d'index avec un message d'erreur en cas de citation introuvable
        if (!$citation) {
            $this->addFlash('danger', 'Action impossible : Référence inexistante.');
            return $this->redirectToRoute('app_citations');
        }

        // Initialisaiton du formulaire de modification prérempli
        $form = $this->createForm(CitationFormType::class, $citation, ['auteur' => $auteurs]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $message = 'Citation modifiée avec succès.';
            $message_type = 'success';

            try {
                $this->citationRepository->save($citation, true);
            } catch (Exception $e) {
                $message = 'Action impossible : ' . $e->getMessage();
                $message_type = 'danger';
            }
            // Retour sur la page d'index avec affichage d'un message
            $this->addFlash($message_type, $message);
            return $this->redirectToRoute('app_citations');
        }

        // Affichage du formulaire de modification prérempli
        return $this->render('citations/modifier.html.twig', [
            'controller_name' => 'CitationsController',
            'citation' => $citation,
            'citationForm' => $form->createView()
        ]);
    }

    /**
     * Ajoute une nouvelle citation.
     *
     * @param Request $request Informations sur la citation à créer, transmises via POST.
     * @return Reponse Vue Twig affichant un formulaire de création ou un message.
     */
    #[Route('/citation/ajouter/', name: 'app_citations_ajouter')]
    public function ajouter(Request $request): Response
    {
        // Création d'une entité citation
        $citation = new Citation();

        // Récupération de la liste des auteurs
        $auteurs = $this->auteurRepository->findBy([], ['auteur' => 'ASC']);

        // Initialisation du formulaire de création
        $form = $this->createForm(CitationFormType::class, $citation, ['auteur' => $auteurs]);
        $form->handleRequest($request);

        // Enregistrement des informations en cas soumission
        if ($form->isSubmitted() && $form->isValid()) {

            $message = 'Nouvelle citation créée avec succès.';
            $message_type = 'success';

            try {
                $this->citationRepository->save($citation, true);
            } catch (Exception $e) {
                $message = 'Action impossible : ' . $e->getMessage();
                $message_type = 'danger';
            }
            // Retour sur la page d'index avec affichage d'un message
            $this->addFlash($message_type, $message);
            return $this->redirectToRoute('app_citations');
        }

        // Affichage du formulaire de création
        return $this->render('citations/ajouter.html.twig', [
            'controller_name' => 'CitationsController',
            'citationForm' => $form->createView()
        ]);
    }

    /**
     * Supprime une citation sélectionnée par son ID.
     * 
     * @param int $id L'ID d'une citation.
     * @return Reponse Vue Twig affichant un message.
     */
    #[Route('/citation/supprimer/{id}', name: 'app_citations_supprimer')]
    public function suppression(int $id): Response
    {
        // Récupération de la citation via son ID
        $citation = $this->citationRepository->find($id);

        // Retour sur la page d'index avec affichage d'un lessage si la citation n'existe pas
        if (!$citation) {
            $this->addFlash('danger', 'Action impossible : Référence inexistante.');
            return $this->redirectToRoute('app_citations');
        }

        // Suppresion de la citation
        $this->citationRepository->remove($citation, true);

        // Retour sur la page d'index avec affichage d'un message de réussite
        $this->addFlash('success', 'La citation a été effacée.');
        return $this->redirectToRoute('app_citations');
    }
}

templates/citations/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout d'une nouvelle citation{% endblock %}

{% block main %}

<div class="row">
    <div class="col-sm-10 col-md-8 col-lg-6 mx-auto">

        {{ form_errors(citationForm) }}

        {{ form_start(citationForm) }}
        <h1 class="h3 mb-3 font-weight-normal">Ajout d'une nouvelle citation</h1>
        {{ form_row(citationForm.auteur_id) }}
        {{ form_row(citationForm.citation) }}
        {{ form_row(citationForm.explication) }}
        <div class="d-flex justify-content-between">
            <a class="btn btn-lg btn-outline-danger mt-3" href="{{ path('app_citations') }}">Annuler</a>
            <button type="submit" class="btn btn-lg btn-outline-success mt-3">Ajouter</button>
        </div>
        {{ form_end(citationForm) }}

    </div>
</div>

{% endblock %}

templates/citations/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}La citation en détails{% endblock %}

{% block main %}

<section>
    <div class="d-flex justify-content-between">
        <h1>La citation en détails</h1>
        <span class="align-bottom">Fiche mise à jour le {{ citation.datemodif|date("d/m/Y à H:i:s") }}</span>
    </div>
    <p class="fs-3">{{ citation.citation|e}}</p>
    {% if citation.explication %}
    <h2 class="h3">Excplication</h2>
    <p>{{ citation.explication|e}}</p>
    {% else %}
    <p class="text-center">Aucune explication enregistrée</p>
    {% endif %}
    {% if citation.auteurId %}
    <p class="text-end fst-italic fs-4">{{ citation.auteurId.auteur }}</p>
    {% else %}
    <p class="text-end fst-italic fs-4">- Anonyme -</p>
    {% endif %}
    {% if is_granted('ROLE_TESTER') %}
    <div class="text-end">
        <a class="btn btn-outline-primary m-1" href="{{ path('app_citations_modifier', {id: citation.id}) }}"
            role="button">Modifier</a>
        <a class="btn btn-outline-danger m-1" href="{{ path('app_citations_supprimer', {id: citation.id}) }}"
            role="button">Supprimer</a>
    </div>
    {% endif %}
</section>

{% endblock %}

templates/citations/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les citations{% endblock %}

{% block main %}

<div class="d-flex align-items-center justify-content-between">
    <h1 class="h3">Liste des citations</h1>
    {% if is_granted('ROLE_TESTER') %}
    <div>
        <a class="btn btn-outline-success m-1" href="{{ path('app_citations_ajouter') }}" role="button">Ajouter une
            citation</a>
    </div>
    {% endif %}
</div>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th class="">Citation</th>
            <th class="">Auteur</th>
            <th class="">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for citation in citations %}
        <tr>
            <td>
                {% if citation.citation|length > 100 %}
                {{ citation.citation|slice(0,100)~'[...]' }}
                {% elseif citation.citation|length <= 100 %} {{ citation.citation}} {% endif %} </td>
            <td>
                {% if citation.auteurId == NULL %}
                - Anonyme -
                {% else %}
                {{ citation.auteurId.auteur }}
                {% endif %}
            </td>
            <td class="align-middle">
                {% if is_granted('ROLE_TESTER') %}
                <a class="btn btn-outline-primary m-1" href="{{ path('app_citations_detail', {id: citation.id}) }}"
                    role="button">Afficher/Modifier</a>
                <a class="btn btn-outline-danger m-1" href="{{ path('app_citations_supprimer', {id: citation.id}) }}"
                    role="button">Supprimer</a>
                {% else %}
                <a class="btn btn-outline-primary m-1" href="{{ path('app_citations_detail', {id: citation.id}) }}"
                    role="button">Afficher</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/citations/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification de la citation{% endblock %}

{% block main %}

<div class="row">
    <div class="col-sm-10 col-md-8 col-lg-6 mx-auto">

        {{ form_errors(citationForm) }}

        {{ form_start(citationForm) }}
        <h1 class="h3 mb-3 font-weight-normal">Modification de la citation</h1>
        {{ form_row(citationForm.auteur_id) }}
        {{ form_row(citationForm.citation) }}
        {{ form_row(citationForm.explication) }}
        <div class="d-flex justify-content-between">
            <a class="btn btn-lg btn-outline-danger mt-3" href="{{ path('app_citations') }}">Annuler</a>
            <button type="submit" class="btn btn-lg btn-outline-primary mt-3">Modifier</button>
        </div>
        {{ form_end(citationForm) }}

    </div>
</div>

{% endblock %}